// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListScreenshots() {
  return window['go']['services']['ScreenshotListService']['ListScreenshots']();
}

export function OpenScreenshot(arg1) {
  return window['go']['services']['ScreenshotListService']['OpenScreenshot'](arg1);
}
