// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ListScreenshots():Promise<Array<services.ScreenshotFile>>;

export function OpenScreenshot(arg1:string):Promise<void>;
