// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function AddTodo(arg1:string):Promise<models.Todo>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetTodos():Promise<Array<models.Todo>>;

export function OCRFromClipboard():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function UpdateTodo(arg1:string,arg2:string,arg3:boolean):Promise<models.Todo>;
