// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function ListScreenshots() {
  return window['go']['main']['App']['ListScreenshots']();
}

export function OCRFromClipboard() {
  return window['go']['main']['App']['OCRFromClipboard']();
}

export function OpenScreenshot(arg1) {
  return window['go']['main']['App']['OpenScreenshot'](arg1);
}

export function OptimizePrompt(arg1, arg2) {
  return window['go']['main']['App']['OptimizePrompt'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2, arg3);
}
